server:
  port: 8080
  serverAddress: 15.165.215.22 # AWs EC2 탄력적IP주소
  servlet:
    session:
      persistent: false # 기본값은 false지만 spring-boot-devtools 라이브러리가 true로 설정(재시작/핫 리로드기능때문?)하기때문에 명시해주는것이 좋다
      timeout: 70s # 60초 CustomLoginSuccessHandler.java 에 개별세션에대한 타임아웃설정이 우선
#      cookie:
#        max-age: 1s # 기본단위 초

serverName: blue_server

spring:
  thymeleaf:
    cache: false
    prefix: classpath:/templates
    suffix: .html

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/mydb # ;NON_KEYWORDS=USER 예약어 user 강제해제
    username: root
    password: 1234
  #    AWD RDS 연결(url변경)
  #    driver-class-name: com.mysql.cj.jdbc.Driver
  #    url: jdbc:mysql://rds-mysql.cpag6cmwknpz.us-east-1.rds.amazonaws.com:3306/rds_mysql # ;NON_KEYWORDS=USER 예약어 user 강제해제
  #    username: admin
  #    password: qwerasdf

  h2:
    console:
      enabled: true

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL57Dialect
        hbm2ddl:
          auto: update
          show-sql: true
  #    hibernate:
  #      ddl-auto: create
  #      show-sql: true

  security:
    oauth2:
      client:
        #registration
        registration:
          #Naver
          naver: # /oauth2/authorization/naver 이 주소를 동작하게 한다.
            client-id: lpGKOqlteC6kzWSrKNRE
            client-secret: ssibXfykyI
            redirect-uri: http://15.165.215.22/login/oauth2/code/naver #필수, 네이버 설정과 똑같아야한다
            authorization-grant-type: authorization_code
            scope:
              - name # 작대기 다음에 띄어쓰기 필수
              - email
              - profile_image
            client-name: Naver

          #카카오
          kakao:
            client-id: 372a19bda5132847ec1232e2c9d97ee9
            client-secret: lEAUlTIQbOq7iWgyxapHQE2gBLLZaRGt
            client-authentication-method: client_secret_post
            authorization-grant-type: authorization_code
            scope: # https://developers.kakao.com/docs/latest/ko/kakaologin/common#user-info
              - profile_nickname
              - profile_image
            #              - account_email
            redirect-uri: http://15.165.215.22/login/oauth2/code/kakao
            client-name: Kakao

          #Google
          google:
            client-id: 362737595673-t6gr8o5ehldlnmfk3bcu0ce6bc9p32a7.apps.googleusercontent.com
            client-secret: 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
            #구글 자체에서 설정되어있기때문에 설정안해도 됨
            #            redirect-uri: http://localhost:8080/login/oauth2/code/google
            scope:
              - email
              - profile

        #privider
        provider:
          # 네이버는 OAuth2.0 공식 지원대상이 아니라서 provider 설정이 필요하다.
          # 요청주소도 다르고, 응답 데이터도 다르기 때문이다.
          # provider 영역은 반드시 registration를 모두 기입한 후 설정해야한다
          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize #네이버로그인 아이콘을 클릭하면 실제로 전달하는주소
            token-uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user-name-attribute: response #회원정보를 JSON으로 받는대 response라는 키값으로 받는다

          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-info-authentication-method: header
            user-name-attribute: id # Kakao 응답 값 id, connected_at, properties, kakao_account 중 id 지정

mybatis:
  mapper-locations: classpath:mappers/*.xml
  type-aliases-package: com.footfix.dto, com.footfix.security.dto

my:
  api-football:
    url: https://api-football-v1.p.rapidapi.com/v3/fixtures?league=39&season=2024
    X-RapidAPI-Key: fdb46b1dd2mshfffc30dd6148d48p184ec9jsnec7b76890cf0
    X-RapidAPI-Host: api-football-v1.p.rapidapi.com

fcm:
  key:
    path: src/main/resources/footfix-f417c-firebase-adminsdk-7fwsl-8e0ba158e8.json
    scope: https://www.googleapis.com/auth/cloud-platform

iamport:
  api_key: 4547006440043313
  api_secret: hz10YM2X7doI10MPhrUcEsY7MHTXyfGZIXFOKfyA62kqk4VWy4fxlaDW7vh4sEgjD0UaRUjSqLoC0WIM
